format = """
$username\
$hostname\
$time\
$directory\
$git_status\
$line_break\
$character"""

[directory]
style = 'blue'

[git_status]
format = '[\[$all_status$ahead_behind\]]($style) '
style = 'bright-black'

[time]
disabled = false
format = '[$time]($style) '
style = 'yellow'
time_format = '%F %T'
