format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$fill\
$time\
$line_break\
$character"""

[directory]
style = "blue"
truncate_to_repo = false
truncation_length = 0

[fill]
symbol = ' '

[git_branch]
format = "[$branch]($style)"
style = "purple"

[git_status]
style = "bright-black"

[git_state]
style = "bright-black"

[time]
disabled = false
format = '[$time]($style)'
style = 'yellow'
time_format = '%F %T'
