format = """
$username\
$hostname\
$time\
$line_break\
$directory\
$git_status\
$line_break\
$character
"""

[directory]
style = '#66d9ef'

[git_status]
format = '[\[$all_status$ahead_behind\]]($style) '
style = 'purple'

[time]
disabled = false
format = '[$time]($style) '
style = 'bright-black'
time_format = '%F %T'
