" Vim configuration.
" Copy or symlink to ~/.vimrc.
"
set nocompatible

" plugins
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'elixir-lang/vim-elixir'
Plugin 'jonnyjohannes/vim-charmm'
Plugin 'jonnyjohannes/vim-demon'
Plugin 'kien/ctrlp.vim'
Plugin 'lervag/vimtex'
Plugin 'mxw/vim-jsx'
Plugin 'pangloss/vim-javascript'
Plugin 'sainnhe/sonokai'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-rails'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
call vundle#end()

" colours
syntax enable
set termguicolors
let g:sonokai_style = 'maia'
colorscheme sonokai

" commands
set backspace=indent,eol,start    " Intuitive backspacing.
set ignorecase                    " Case-insensitive searching.
set smartcase                     " But case-sensitive if expression contains a capital letter.
set number                        " Show line numbers.
set incsearch                     " Highlight matches as you type.
set hlsearch                      " Highlight matches.
set laststatus=2                  " Show the status line all the time
set splitbelow                    " split horizontal pane to the bottom
set splitright                    " split vertical pane to the right
set clipboard=unnamed             " Share system clipboard
set tabstop=2                     " tab size: 2
set shiftwidth=2                  " tab size with `<<`/`>>`: 2
set shiftround                    " use multiple of shiftwidth
set expandtab                     " use softtabs

" airline
let g:airline_theme='sonokai'
let g:airline_extensions = []
let g:airline_left_sep = ''
let g:airline_right_sep = ''
let g:airline_section_x = ''
let g:airline_section_y = ''
let g:airline_section_z = '%l/%L : %c'

" filetypes
filetype plugin indent on
au BufRead,BufNewFile *.hql* set filetype=sql
let g:markdown_fenced_languages = ['java', 'python', 'sh']
