# monokai-pro
[colors.primary]
background = '#1a1a1a'
foreground = '#e0e0e0'

[colors.normal]
black   = '#2c2525'
red     = '#fd6883'
green   = '#adda78'
yellow  = '#f9cc6c'
blue    = '#66d9ef'
magenta = '#a8a9eb'
cyan    = '#85dacc'
white   = '#fff1f3'

[colors.bright]
black   = '#72696a'
red     = '#fd6883'
green   = '#adda78'
yellow  = '#f9cc6c'
blue    = '#66d9ef'
magenta = '#a8a9eb'
cyan    = '#85dacc'
white   = '#fff1f3'
