" (neo)vim configuration
set nocompatible

" plugins
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'junegunn/fzf'
Plugin 'junegunn/fzf.vim'
Plugin 'sainnhe/sonokai'
Plugin 'sheerun/vim-polyglot'
Plugin 'tpope/vim-fugitive'
Plugin 'vim-airline/vim-airline'
call vundle#end()

" colours
syntax enable
set termguicolors
let g:sonokai_style = 'shusia'
colorscheme sonokai
hi Visual ctermbg=237 guibg=#4c4c00

" basics
let mapleader = ','

set ignorecase                    " case-insensitive searching
set smartcase                     " but case-sensitive if expression contains a capital letter
set number                        " show line numbers
set incsearch                     " highlight matches as you type.
set hlsearch                      " highlight matches.
set splitbelow                    " split horizontal pane to the bottom
set splitright                    " split vertical pane to the right
set clipboard=unnamed             " share system clipboard
set shiftround                    " use multiple of shiftwidth
set expandtab                     " use softtabs
set mouse=v                       " enable mouse in visual mode
set nofixeol                      " no newlines at the end of files
set nofixendofline                " no newlines at the end of files

" airline
let g:airline_theme='sonokai'
let g:airline_extensions = ['branch']
let g:airline_section_a = ''
let g:airline_section_a = '%{airline#util#wrap(airline#parts#mode(),0)}'
let g:airline_section_b = ''
let g:airline_section_c = '%f'
let g:airline_section_x = '%{&filetype}'
let g:airline_section_y = '%l:%c'
let g:airline_section_z = ''

" fzf
nnoremap <leader>b :Buffers<cr>
nnoremap <leader>f :Rg<cr>
nnoremap <leader>t :Files<cr>
