set nocompatible                  " (neo)vim compatible
set cursorline                    " highlight current line
set number                        " show line numbers
set relativenumber                " show relative line numbers
set ignorecase                    " case-insensitive searching
set smartcase                     " but case-sensitive if expression contains a capital letter
set incsearch                     " highlight matches as you type
set hlsearch                      " highlight matches.
set splitbelow                    " split horizontal pane to the bottom
set splitright                    " split vertical pane to the right
set shiftround                    " use multiple of shiftwidth
set expandtab                     " use softtabs
set clipboard=unnamed             " share system clipboard
set mouse=v                       " enable mouse in visual mode
set nofixendofline                " no newlines at the end of files
set noshowmode                    " no mode in command line
set fillchars=eob:\               " blank end of buffers

let mapleader = ' '

augroup NormalModeOverrides
  autocmd!
  " Centre screen after page movements
  nnoremap <C-d> <C-d>zz
  nnoremap <C-u> <C-u>zz
  " Centre screen when navigating search results
  nnoremap n nzzzv
  nnoremap N Nzzzv
  " buffer (tmux-ish) navigation
  nnoremap <leader>l :b#<cr>
  nnoremap <leader>x :confirm bd<cr>
  nnoremap <leader>z :only<cr>
augroup END

augroup VisualModeOverrides
  autocmd!
  " Move selected lines up and down
  vnoremap J :m '>+1<CR>gv=gv
  vnoremap K :m '<-2<CR>gv=gv
augroup END

