# vim keybindings
bindkey -v

# set default editors
export EDITOR=vim
export VISUAL=vim

# exectuable PATHs
export PATH=/opt/homebrew/bin:$PATH
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/src/bin:$PATH

# env management
eval "$(mise activate zsh)"

# fzf
source <(fzf --zsh)
export FZF_DEFAULT_OPTS='--height 50% --layout reverse'

# starship prompt configs
export STARSHIP_CONFIG=$HOME/.config/starship/starship.toml
eval "$(starship init zsh)"

# autocompletion
autoload -U compinit
compinit

# aliases
alias ls='ls -G'
alias vi='nvim .'

# local config file
[[ -s ~/.config/zsh/zsh.local ]] && source ~/.config/zsh/zsh.local

